stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: kkemis/vwa
  IMAGE_TAG: latest


run_tests:
   stage: test
   image: python:3.9-slim-buster
   allow_failure: true
   only:
    - main
   before_script:
     - python --version
     - pip install -r src/requirements.txt
     # - npm install -g html-validate
     - cd src/
   script:
     # - npx html-validate
     - flake8 app.py
     - mypy --strict app.py


build_image:
  stage: build
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG


deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY vwaadmin@20.16.172.53 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker pull $IMAGE_NAME:$IMAGE_TAG && docker container rm -f vwa || true &&
        docker run -d --name vwa -p 80:5000 $IMAGE_NAME:$IMAGE_TAG"
